import api from './axios';

export const liveClassService = {
    /**
     * Create a new live class
     * Teacher only
     */
    async createLiveClass(data) {
        const response = await api.post('/live-classes', data);
        return response.data;
    },

    /**
     * Get live class details
     */
    async getLiveClassDetails(id) {
        const response = await api.get(`/live-classes/${id}`);
        return response.data;
    },

    /**
     * Get all live classes for a course
     */
    async getCourseLiveClasses(courseId) {
        const response = await api.get(
            `/live-classes/course/${courseId}`
        );

        return response.data;
    },

    /**
     * Get Agora token
     *
     * uid is generated by frontend and sent to backend.
     * Backend generates the token for this exact UID.
     */
    async getAgoraToken(id, uid) {
        const response = await api.post(
            `/live-classes/${id}/token`,
            {
                uid,
            }
        );

        return response.data;
    },

    /**
     * Start live class
     * Teacher only
     */
    async startLiveClass(id) {
        const response = await api.put(
            `/live-classes/${id}/start`
        );

        return response.data;
    },

    /**
     * End live class
     * Teacher only
     */
    async endLiveClass(id) {
        const response = await api.put(
            `/live-classes/${id}/end`
        );

        return response.data;
    },

    /**
     * Leave live class
     */
    async leaveLiveClass(id) {
        const response = await api.post(
            `/live-classes/${id}/leave`
        );

        return response.data;
    },
};